/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlykhachsan_btl;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/**
 *
 * @author ADMIN
 */
public class DatPhong extends javax.swing.JFrame {

    /**
     * Creates new form datphong
     */
    Connection connection;
    String maPhong;

    public DatPhong() {
        initComponents();
        jTextField_hoTen.requestFocus();
        GenericClass.centerOnScreen(this);
        try {
            connection = DBConnector.connect();
        } catch (SQLException ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clear_input() {
        jTextField_hoTen.requestFocus();
        jTextField_hoTen.setText("");
        jTextField_soDienThoai.setText("");
        jTextField_maKhachHang.setText("");
        jDateChooser_ngayDen.setDate(null);
        jDateChooser_ngayDi.setDate(null);
        jTextField_soNguoi.setText("");
    }

    private void loadPhong(String query) {
        try {
            // Clear the table before loading new data
            DefaultTableModel model = (DefaultTableModel) jTable_dsPhong.getModel();
            model.setRowCount(0);

            // Create a PreparedStatement with the provided query
            java.sql.PreparedStatement pst = connection.prepareStatement(query);

            // Set values for the parameters in the SQL statement
            pst.setString(1, jComboBox_loaiPhong.getSelectedItem().toString());
            pst.setString(2, jComboBox_hangPhong.getSelectedItem().toString());

            // Execute the query
            ResultSet resultSet = pst.executeQuery();

            while (resultSet.next()) {
                // Retrieve data from the result set and add it to the table model
                Object[] col = new Object[5];
                col[0] = resultSet.getObject(1);
                col[1] = resultSet.getObject(2);
                col[2] = resultSet.getObject(3);
                col[3] = resultSet.getObject(4);
                col[4] = resultSet.getObject(5);
                model.addRow(col);
            }

            // Close the result set and the prepared statement
            resultSet.close();
            pst.close();
        } catch (SQLException ex) {
            Logger.getLogger(DatPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_dsPhong = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jComboBox_hangPhong = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_loaiPhong = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_hoTen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_soDienThoai = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField_maKhachHang = new javax.swing.JTextField();
        jDateChooser_ngayDi = new com.toedter.calendar.JDateChooser();
        jDateChooser_ngayDen = new com.toedter.calendar.JDateChooser();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField_soNguoi = new javax.swing.JTextField();
        jButton_dat = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đặt phòng");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách phòng trống"));

        jTable_dsPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Loại phòng", "Hạng phòng", "Vị trí", "Giá thuê"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_dsPhong.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_dsPhong.setShowGrid(true);
        jTable_dsPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_dsPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_dsPhong);
        if (jTable_dsPhong.getColumnModel().getColumnCount() > 0) {
            jTable_dsPhong.getColumnModel().getColumn(0).setResizable(false);
            jTable_dsPhong.getColumnModel().getColumn(1).setResizable(false);
            jTable_dsPhong.getColumnModel().getColumn(2).setResizable(false);
            jTable_dsPhong.getColumnModel().getColumn(3).setResizable(false);
            jTable_dsPhong.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin phòng"));

        jComboBox_hangPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiêu chuẩn", "Cao cấp", "Sang trọng", "Thượng hạng" }));
        jComboBox_hangPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_hangPhongActionPerformed(evt);
            }
        });

        jLabel3.setText("Hạng phòng:");

        jLabel4.setText("Loại phòng:");

        jComboBox_loaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SGL", "TWN", "DBL", "TRPL", " " }));
        jComboBox_loaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_loaiPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49))
                    .addComponent(jComboBox_loaiPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_hangPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(56, 56, 56)))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_hangPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_loaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khách hàng"));

        jLabel5.setText("Họ tên:");

        jTextField_hoTen.setNextFocusableComponent(jTextField_soDienThoai);
        jTextField_hoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_hoTenKeyTyped(evt);
            }
        });

        jLabel6.setText("Số điện thoại:");

        jTextField_soDienThoai.setNextFocusableComponent(jTextField_maKhachHang);
        jTextField_soDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_KeyTyped(evt);
            }
        });

        jLabel31.setText("Căn cước công dân:");

        jTextField_maKhachHang.setNextFocusableComponent(jDateChooser_ngayDen);
        jTextField_maKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_KeyTyped(evt);
            }
        });

        jDateChooser_ngayDi.setNextFocusableComponent(jTextField_soNguoi);

        jDateChooser_ngayDen.setNextFocusableComponent(jDateChooser_ngayDi);

        jLabel32.setText("Ngày đến:");

        jLabel33.setText("Ngày đi:");

        jLabel34.setText("Số người:");

        jTextField_soNguoi.setNextFocusableComponent(jButton_dat);
        jTextField_soNguoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_KeyTyped(evt);
            }
        });

        jButton_dat.setText("Đặt");
        jButton_dat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_datActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_soDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jTextField_hoTen)
                    .addComponent(jTextField_maKhachHang)
                    .addComponent(jLabel6)
                    .addComponent(jLabel31))
                .addGap(65, 65, 65)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser_ngayDi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser_ngayDen, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jTextField_soNguoi)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32))
                .addGap(65, 65, 65)
                .addComponent(jButton_dat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser_ngayDen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jTextField_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_soDienThoai)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jDateChooser_ngayDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_dat)
                        .addGap(4, 4, 4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_maKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_soNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Chú thích"));

        jLabel43.setText("SGL: 1 giường đơn");

        jLabel44.setText("TWN: 2 giường đơn");

        jLabel45.setText("DBL: 1 giường đôi");

        jLabel46.setText("TRPL: 1 giường đôi 1 giường đơn");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(70, 70, 70))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(79, 79, 79))
                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_datActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_datActionPerformed
        // TODO add your handling code here:
        try {
            // Lấy dữ liệu từ các component
            String hoTen = jTextField_hoTen.getText();
            String maKhachHang = jTextField_maKhachHang.getText();
            String soDienThoai = jTextField_soDienThoai.getText();
            Date ngayDen = GenericClass.getDateFromDateChooser(jDateChooser_ngayDen);
            Date ngayDi = GenericClass.getDateFromDateChooser(jDateChooser_ngayDi);
            int soNguoi = Integer.parseInt(jTextField_soNguoi.getText());

            // Kiểm tra nếu một trong các trường là trống
            if (hoTen.isEmpty() || maKhachHang.isEmpty() || soDienThoai.isEmpty() || soNguoi < 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else if (ngayDen.after(ngayDi)) {
                // Kiểm tra nếu ngày đến sau ngày đi
                JOptionPane.showMessageDialog(this, "Ngày đến phải trước ngày đi.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else {
                // Thêm dữ liệu vào cơ sở dữ liệu
                String query = "INSERT INTO khachhang(MaKhachHang, HoTen, SoDienThoai, NgayDen, NgayDi, SoNguoi, MaPhong) VALUES (?, ?, ?, ?, ?, ?, ?)";
                try (java.sql.PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                    preparedStatement.setString(1, maKhachHang);
                    preparedStatement.setString(2, hoTen);
                    preparedStatement.setString(3, soDienThoai);
                    preparedStatement.setDate(4, new java.sql.Date(ngayDen.getTime()));
                    preparedStatement.setDate(5, new java.sql.Date(ngayDi.getTime()));
                    preparedStatement.setInt(6, soNguoi);
                    preparedStatement.setString(7, maPhong);

                    // Thực hiện câu lệnh SQL
                    preparedStatement.executeUpdate();
                }
                clear_input();
                GenericClass.updateTinhTrangPhong(connection, maPhong, "Đã đặt");
                JOptionPane.showMessageDialog(this, "Đặt phòng " + maPhong + " thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (HeadlessException | NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi đặt phòng.", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_datActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        loadPhong("SELECT * FROM phong WHERE TinhTrang = 'Trống' AND LoaiPhong = ? AND HangPhong = ?");
    }//GEN-LAST:event_formWindowActivated

    private void jComboBox_hangPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_hangPhongActionPerformed
        // TODO add your handling code here:
        loadPhong("SELECT * FROM phong WHERE TinhTrang = 'Trống' AND LoaiPhong = ? AND HangPhong = ?");
    }//GEN-LAST:event_jComboBox_hangPhongActionPerformed

    private void jComboBox_loaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_loaiPhongActionPerformed
        // TODO add your handling code here:
        loadPhong("SELECT * FROM phong WHERE TinhTrang = 'Trống' AND LoaiPhong = ? AND HangPhong = ?");
    }//GEN-LAST:event_jComboBox_loaiPhongActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        if (GenericClass.isFromThuePhong == true) {
            this.dispose();
            ThuePhong thuePhong = new ThuePhong();
            thuePhong.show();
            GenericClass.isFromThuePhong = false;
        } else {
            this.dispose();
            TrangChu trangChu = new TrangChu();
            trangChu.show();
        }
    }//GEN-LAST:event_formWindowClosed

    private void jTable_dsPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_dsPhongMouseClicked
        // TODO add your handling code here:

        int selectedRow = jTable_dsPhong.getSelectedRow();

        // Lấy dữ liệu từ bảng và gán cho các component
        maPhong = jTable_dsPhong.getValueAt(selectedRow, 0).toString();
    }//GEN-LAST:event_jTable_dsPhongMouseClicked

    private void jTextField_KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_KeyTyped
        // TODO add your handling code here:
        GenericClass.numbersOnly(evt);
    }//GEN-LAST:event_jTextField_KeyTyped

    private void jTextField_hoTenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_hoTenKeyTyped
        // TODO add your handling code here:
        GenericClass.charactersOnly(evt);
    }//GEN-LAST:event_jTextField_hoTenKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_dat;
    private javax.swing.JComboBox<String> jComboBox_hangPhong;
    private javax.swing.JComboBox<String> jComboBox_loaiPhong;
    private com.toedter.calendar.JDateChooser jDateChooser_ngayDen;
    private com.toedter.calendar.JDateChooser jDateChooser_ngayDi;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_dsPhong;
    private javax.swing.JTextField jTextField_hoTen;
    private javax.swing.JTextField jTextField_maKhachHang;
    private javax.swing.JTextField jTextField_soDienThoai;
    private javax.swing.JTextField jTextField_soNguoi;
    // End of variables declaration//GEN-END:variables
}
