/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlykhachsan_btl;

import java.awt.HeadlessException;
import java.awt.List;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.ZoneId;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;

/**
 *
 * @author Admin
 */
public class QuanLyKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyKhachHang
     */
    Connection connection;
    String maPhong_cu, tinhTrang;

    public QuanLyKhachHang() {
        initComponents();
        GenericClass.centerOnScreen(this);
        try {
            connection = DBConnector.connect();
        } catch (SQLException ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadMaPhongTrong() {
        try {
            jComboBox_maPhong.removeAllItems();
            String query = "SELECT MaPhong FROM phong WHERE TinhTrang = 'Trống'";
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery(query);

            while (resultSet.next()) {
                String maPhong = resultSet.getString("MaPhong");
                jComboBox_maPhong.addItem(maPhong);
            }

            resultSet.close();
            statement.close();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void themPhieuDen(String maPhieuDen, String maKhachHang, String maPhong, Date ngayDen, Date ngayDi) {
        try {
            String query = "INSERT INTO phieuden(MaPhieu, MaKhachHang, MaPhong, NgayDen, NgayDi) VALUES (?, ?, ?, ?, ?)";
            try (java.sql.PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                preparedStatement.setString(1, maPhieuDen);
                preparedStatement.setString(2, maKhachHang);
                preparedStatement.setString(3, maPhong);
                preparedStatement.setDate(4, new java.sql.Date(ngayDen.getTime()));
                preparedStatement.setDate(5, new java.sql.Date(ngayDi.getTime()));

                preparedStatement.executeUpdate();
            }
            clear_input();
        } catch (HeadlessException | NumberFormatException | SQLException ex) {
            Logger.getLogger(QuanLyPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setEditable() {
        jTextField_hoTen.setEditable(true);
        jTextField_soDienThoai.setEditable(true);
        jTextField_maKhachHang.setEditable(true);
        jDateChooser_ngayDen.setEnabled(true);
        jDateChooser_ngayDi.setEnabled(true);
        jTextField_soNguoi.setEditable(true);
        jComboBox_maPhong.setEnabled(true);
        jButton_sua.setEnabled(true);
        jButton_xoa.setEnabled(true);
    }

    private void clear_input() {
        jTextField_hoTen.setText("");
        jTextField_hoTen.setEditable(false);
        jTextField_soDienThoai.setText("");
        jTextField_soDienThoai.setEditable(false);
        jTextField_maKhachHang.setText("");
        jTextField_maKhachHang.setEditable(false);
        jDateChooser_ngayDen.setDate(null);
        jDateChooser_ngayDen.setEnabled(false);
        jDateChooser_ngayDi.setDate(null);
        jDateChooser_ngayDi.setEnabled(false);
        jTextField_soNguoi.setText("");
        jTextField_soNguoi.setEditable(false);
        jComboBox_maPhong.removeAllItems();
        loadMaPhongTrong();
        jComboBox_maPhong.setEnabled(false);
        jButton_sua.setEnabled(false);
        jButton_xoa.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_dsKhach = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_hoTen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_soDienThoai = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField_maKhachHang = new javax.swing.JTextField();
        jDateChooser_ngayDi = new com.toedter.calendar.JDateChooser();
        jDateChooser_ngayDen = new com.toedter.calendar.JDateChooser();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField_soNguoi = new javax.swing.JTextField();
        jButton_sua = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_maPhong = new javax.swing.JComboBox<>();
        jButton_xoa = new javax.swing.JButton();
        jTextField_timKiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Khách hàng");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách khách hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTable_dsKhach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ tên", "Số điện thoại", "Căn cước", "Ngày đến", "Ngày đi", "Tình trạng", "Phòng", "Số người"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_dsKhach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_dsKhachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_dsKhach);
        if (jTable_dsKhach.getColumnModel().getColumnCount() > 0) {
            jTable_dsKhach.getColumnModel().getColumn(0).setResizable(false);
            jTable_dsKhach.getColumnModel().getColumn(1).setResizable(false);
            jTable_dsKhach.getColumnModel().getColumn(2).setResizable(false);
            jTable_dsKhach.getColumnModel().getColumn(3).setResizable(false);
            jTable_dsKhach.getColumnModel().getColumn(4).setResizable(false);
            jTable_dsKhach.getColumnModel().getColumn(5).setResizable(false);
            jTable_dsKhach.getColumnModel().getColumn(6).setResizable(false);
            jTable_dsKhach.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khách hàng"));

        jLabel5.setText("Họ tên:");

        jTextField_hoTen.setEditable(false);
        jTextField_hoTen.setNextFocusableComponent(jTextField_soDienThoai);
        jTextField_hoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_hoTenKeyTyped(evt);
            }
        });

        jLabel6.setText("Số điện thoại:");

        jTextField_soDienThoai.setEditable(false);
        jTextField_soDienThoai.setNextFocusableComponent(jTextField_maKhachHang);
        jTextField_soDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_KeyTyped(evt);
            }
        });

        jLabel31.setText("Căn cước công dân:");

        jTextField_maKhachHang.setEditable(false);
        jTextField_maKhachHang.setNextFocusableComponent(jDateChooser_ngayDen);
        jTextField_maKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_KeyTyped(evt);
            }
        });

        jDateChooser_ngayDi.setEnabled(false);
        jDateChooser_ngayDi.setNextFocusableComponent(jTextField_soNguoi);

        jDateChooser_ngayDen.setEnabled(false);
        jDateChooser_ngayDen.setFocusable(false);
        jDateChooser_ngayDen.setNextFocusableComponent(jDateChooser_ngayDi);

        jLabel32.setText("Ngày đến:");

        jLabel33.setText("Ngày đi:");

        jLabel34.setText("Số người:");

        jTextField_soNguoi.setEditable(false);
        jTextField_soNguoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_KeyTyped(evt);
            }
        });

        jButton_sua.setText("Sửa");
        jButton_sua.setEnabled(false);
        jButton_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_suaActionPerformed(evt);
            }
        });

        jLabel4.setText("Chuyển khách đến phòng:");

        jComboBox_maPhong.setEnabled(false);
        jComboBox_maPhong.setNextFocusableComponent(jButton_sua);

        jButton_xoa.setText("Xóa");
        jButton_xoa.setEnabled(false);
        jButton_xoa.setNextFocusableComponent(jButton_xoa);
        jButton_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(161, 161, 161))
                    .addComponent(jTextField_soDienThoai)
                    .addComponent(jTextField_maKhachHang)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(128, 128, 128))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(94, 94, 94))
                    .addComponent(jTextField_hoTen))
                .addGap(65, 65, 65)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser_ngayDi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_soNguoi)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(150, 150, 150))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(156, 156, 156))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(146, 146, 146))
                    .addComponent(jDateChooser_ngayDen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jButton_sua)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_xoa))
                        .addComponent(jComboBox_maPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser_ngayDen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_hoTen)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_maPhong)))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_soDienThoai)
                    .addComponent(jDateChooser_ngayDi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_maKhachHang)
                            .addComponent(jTextField_soNguoi)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jTextField_timKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_timKiemKeyReleased(evt);
            }
        });

        jLabel1.setText("Tìm kiếm khách hàng:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_timKiem)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_dsKhachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_dsKhachMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_dsKhach.getSelectedRow();
        jTextField_hoTen.setText(jTable_dsKhach.getValueAt(selectedRow, 0).toString());
        jTextField_soDienThoai.setText(jTable_dsKhach.getValueAt(selectedRow, 1).toString());
        jTextField_maKhachHang.setText(jTable_dsKhach.getValueAt(selectedRow, 2).toString());
        Object ngayDenValue = jTable_dsKhach.getValueAt(selectedRow, 3);
        if (ngayDenValue instanceof java.time.LocalDateTime) {
            java.time.LocalDateTime ngayDenLocalDateTime = (java.time.LocalDateTime) ngayDenValue;
            java.util.Date ngayDenDate = java.sql.Timestamp.valueOf(ngayDenLocalDateTime);
            jDateChooser_ngayDen.setDate(ngayDenDate);
        }
        Object ngayDiValue = jTable_dsKhach.getValueAt(selectedRow, 4);
        if (ngayDiValue instanceof java.time.LocalDateTime) {
            java.time.LocalDateTime ngayDiLocalDateTime = (java.time.LocalDateTime) ngayDiValue;
            java.util.Date ngayDiDate = java.sql.Timestamp.valueOf(ngayDiLocalDateTime);
            jDateChooser_ngayDi.setDate(ngayDiDate);
        }
        tinhTrang = jTable_dsKhach.getValueAt(selectedRow, 5).toString();
        maPhong_cu = jTable_dsKhach.getValueAt(selectedRow, 6).toString();
        jTextField_soNguoi.setText(jTable_dsKhach.getValueAt(selectedRow, 7).toString());
        setEditable();
    }//GEN-LAST:event_jTable_dsKhachMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        String query = "SELECT kh.HoTen, kh.SoDienThoai, kh.MaKhachHang, kh.NgayDen, kh.NgayDi, p.TinhTrang, p.MaPhong, kh.SoNguoi FROM khachhang kh JOIN phong p ON kh.MaPhong = p.MaPhong WHERE p.TinhTrang <> 'Trống'";
        GenericClass.loadData(connection, query, jTable_dsKhach);
        loadMaPhongTrong();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.dispose();
        TrangChu trangChu = new TrangChu();
        trangChu.show();
    }//GEN-LAST:event_formWindowClosed

    private void jButton_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_suaActionPerformed
        // TODO add your handling code here:
        try {
            // Lấy dữ liệu từ các component
            String hoTen = jTextField_hoTen.getText();
            String maKhachHang = jTextField_maKhachHang.getText();
            String soDienThoai = jTextField_soDienThoai.getText();
            java.util.Date ngayDenDate = jDateChooser_ngayDen.getDate();
            java.util.Date ngayDiDate = jDateChooser_ngayDi.getDate();
            int soNguoi = Integer.parseInt(jTextField_soNguoi.getText());
            String maPhong = jComboBox_maPhong.getSelectedItem().toString();

            // Kiểm tra nếu một trong các trường là trống
            if (hoTen.isEmpty() || maKhachHang.isEmpty() || soDienThoai.isEmpty() || soNguoi < 0 || ngayDenDate == null || ngayDiDate == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else if (ngayDenDate.after(ngayDiDate)) {
                // Kiểm tra nếu ngày đến sau ngày đi
                JOptionPane.showMessageDialog(this, "Ngày đến phải trước ngày đi.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else {
                // Chuyển đổi từ Date sang LocalDateTime (kiểu dữ liệu của cột NgayDen và NgayDi)
                java.time.LocalDateTime ngayDenLocalDateTime = ngayDenDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
                java.time.LocalDateTime ngayDiLocalDateTime = ngayDiDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
                String query = "UPDATE khachhang SET HoTen = ?, SoDienThoai = ?, NgayDen = ?, NgayDi = ?, SoNguoi = ?, MaPhong = ? WHERE MaKhachHang = ?";
                try (java.sql.PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                    preparedStatement.setString(1, hoTen);
                    preparedStatement.setString(2, soDienThoai);
                    preparedStatement.setObject(3, ngayDenLocalDateTime);
                    preparedStatement.setObject(4, ngayDiLocalDateTime);
                    preparedStatement.setInt(5, soNguoi);
                    preparedStatement.setString(6, maPhong);
                    preparedStatement.setString(7, maKhachHang);

                    // Thực hiện câu lệnh SQL
                    preparedStatement.executeUpdate();

                    clear_input();
                    GenericClass.updateCSDL(connection, "DELETE FROM phieuden WHERE MaPhong = ?", maPhong_cu);
                    if (tinhTrang.equalsIgnoreCase("Đã thuê")) {
                        themPhieuDen(GenericClass.generateRandomString("pd", 1000, 9000), maKhachHang, maPhong, ngayDenDate, ngayDiDate);
                    }
                    GenericClass.updateTinhTrangPhong(connection, maPhong, tinhTrang);
                    GenericClass.updateTinhTrangPhong(connection, maPhong_cu, "Trống");
                    JOptionPane.showMessageDialog(this, "Cập nhật khách hàng " + hoTen + " thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (HeadlessException | NumberFormatException | SQLException ex) {
            Logger.getLogger(QuanLyPhong.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật.", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_suaActionPerformed

    private void jButton_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xoaActionPerformed
        // TODO add your handling code here:
        int[] selectedRows = jTable_dsKhach.getSelectedRows();

        if (selectedRows.length > 0) {
            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa " + selectedRows.length + " khách hàng đã chọn?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                try {
                    for (int i = selectedRows.length - 1; i >= 0; i--) {
                        String maPhong = jTable_dsKhach.getValueAt(selectedRows[i], 6).toString();
                        String maKhachHang = jTable_dsKhach.getValueAt(selectedRows[i], 2).toString();
                        String deleteQuery = "DELETE FROM khachhang WHERE MaKhachHang = ?";
                        try (java.sql.PreparedStatement preparedStatement = connection.prepareStatement(deleteQuery)) {
                            preparedStatement.setString(1, maKhachHang);
                            preparedStatement.executeUpdate();
                        }
                        DefaultTableModel model = (DefaultTableModel) jTable_dsKhach.getModel();
                        GenericClass.updateTinhTrangPhong(connection, maPhong, "Trống");
                        model.removeRow(selectedRows[i]);
                    }
                    JOptionPane.showMessageDialog(this, "Đã xóa " + selectedRows.length + " khách hàng.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLyPhong.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Lỗi khi xóa khách hàng: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ít nhất một dòng để xóa.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_xoaActionPerformed

    private void jTextField_KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_KeyTyped
        // TODO add your handling code here:
        GenericClass.numbersOnly(evt);
    }//GEN-LAST:event_jTextField_KeyTyped

    private void jTextField_hoTenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_hoTenKeyTyped
        // TODO add your handling code here:
        GenericClass.charactersOnly(evt);
    }//GEN-LAST:event_jTextField_hoTenKeyTyped

    private void jTextField_timKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_timKiemKeyReleased
        // TODO add your handling code here:
        String query = "SELECT kh.HoTen, kh.SoDienThoai, kh.MaKhachHang, kh.NgayDen, kh.NgayDi, p.TinhTrang, p.MaPhong, kh.SoNguoi FROM khachhang kh JOIN phong p ON kh.MaPhong = p.MaPhong WHERE p.TinhTrang <> 'Trống' AND kh.MaKhachHang LIKE '%" + jTextField_timKiem.getText() + "%'";
        GenericClass.loadData(connection, query, jTable_dsKhach);
    }//GEN-LAST:event_jTextField_timKiemKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_sua;
    private javax.swing.JButton jButton_xoa;
    private javax.swing.JComboBox<String> jComboBox_maPhong;
    private com.toedter.calendar.JDateChooser jDateChooser_ngayDen;
    private com.toedter.calendar.JDateChooser jDateChooser_ngayDi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_dsKhach;
    private javax.swing.JTextField jTextField_hoTen;
    private javax.swing.JTextField jTextField_maKhachHang;
    private javax.swing.JTextField jTextField_soDienThoai;
    private javax.swing.JTextField jTextField_soNguoi;
    private javax.swing.JTextField jTextField_timKiem;
    // End of variables declaration//GEN-END:variables
}
