/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlykhachsan_btl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author itsHuaan
 */
public class ThanhToan extends javax.swing.JFrame {

    /**
     * Creates new form ThanhToans
     */
    Connection connection;
    boolean visibility = false;
    String maPhong;
    LocalDateTime ngayDen, ngayDi;
    int soNgay;
    double chiPhiPhong, chiPhiDichVu, thanhTien;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");

    public ThanhToan() {
        initComponents();
        GenericClass.centerOnScreen(this);
        try {
            connection = DBConnector.connect();
        } catch (SQLException ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisibility(visibility);
    }

    private void loadData() {
        try {
            DefaultTableModel model = (DefaultTableModel) jTable_dsPhong.getModel();
            model.setRowCount(0);

            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT kh.*, p.TinhTrang FROM khachhang kh JOIN phong p ON kh.MaPhong = p.MaPhong WHERE p.TinhTrang = 'Đã thuê'");

            while (resultSet.next()) {
                Object[] col = new Object[3];
                col[0] = resultSet.getObject(2);
                col[1] = resultSet.getObject(1);
                col[2] = resultSet.getObject(7);
                model.addRow(col);
            }

            resultSet.close();
            statement.close();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }

    private void setVisibility(boolean visibility) {
        jLabel_tenKhachHang.setVisible(visibility);
        jLabel_canCuoc.setVisible(visibility);
        jLabel_ngayDen.setVisible(visibility);
        jLabel_ngayDi.setVisible(visibility);
        jLabel_ngaySuDung.setVisible(visibility);
        jLabel_thongTinPhong.setVisible(visibility);
        jLabel_thongTinDichVu.setVisible(visibility);
        jLabel_chiPhiPhong.setVisible(visibility);
        jLabel_chiPhiDichVu.setVisible(visibility);
        jLabel_thanhTien.setVisible(visibility);
    }

    private Double layChiPhi(String query, String parameter) {
        double chiPhi = 0;
        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setObject(1, parameter);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                while (resultSet.next()) {
                    chiPhi += resultSet.getDouble(1);
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return chiPhi;
    }

    private String layThongTin(String query, String parameter) {
        String thongTin = null;
        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setObject(1, parameter);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                while (resultSet.next()) {
                    thongTin = resultSet.getString(1);
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return thongTin;
    }

    private void laySoNgay(String parameter) {
        String query = "SELECT * FROM khachhang WHERE MaPhong = ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setString(1, parameter);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    ngayDen = (LocalDateTime) resultSet.getObject(4);
                    ngayDi = (LocalDateTime) resultSet.getObject(5);
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        Period period = Period.between(ngayDen.toLocalDate(), ngayDi.toLocalDate());
        soNgay = period.getDays();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_canCuoc = new javax.swing.JLabel();
        jLabel_ngayDen = new javax.swing.JLabel();
        jLabel_ngayDi = new javax.swing.JLabel();
        jLabel_ngaySuDung = new javax.swing.JLabel();
        jLabel_tenKhachHang = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_chiPhiPhong = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_thongTinPhong = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel_thongTinDichVu = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel_chiPhiDichVu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton_thanhToan = new javax.swing.JButton();
        jLabel_thanhTien = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_dsPhong = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thanh toán");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        jLabel1.setText("Tên khách hàng:");

        jLabel2.setText("Căn cước công dân:");

        jLabel3.setText("Ngày nhận phòng:");

        jLabel4.setText("Ngày trả phòng:");

        jLabel5.setText("Số ngày sử dụng:");

        jLabel_canCuoc.setText("000000000");

        jLabel_ngayDen.setText("000000000");

        jLabel_ngayDi.setText("000000000");

        jLabel_ngaySuDung.setText("000000000");

        jLabel_tenKhachHang.setText("000000000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_tenKhachHang)
                    .addComponent(jLabel_ngaySuDung)
                    .addComponent(jLabel_ngayDi)
                    .addComponent(jLabel_ngayDen)
                    .addComponent(jLabel_canCuoc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_tenKhachHang))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_canCuoc))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_ngayDen))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_ngayDi))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel_ngaySuDung))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết thanh toán", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel_chiPhiPhong.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_chiPhiPhong.setForeground(new java.awt.Color(187, 0, 0));
        jLabel_chiPhiPhong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_chiPhiPhong.setText("000000");

        jLabel8.setText("Phòng: ");

        jLabel_thongTinPhong.setText("000000000");

        jLabel9.setText("Chi phí:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Giá phòng");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Giá dịch vụ");

        jLabel12.setText("Số lượng dịch vụ sử dụng:");

        jLabel_thongTinDichVu.setText("000000000");

        jLabel13.setText("Chi phí:");

        jLabel_chiPhiDichVu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_chiPhiDichVu.setForeground(new java.awt.Color(187, 0, 0));
        jLabel_chiPhiDichVu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_chiPhiDichVu.setText("000000");

        jButton_thanhToan.setText("Thanh toán");
        jButton_thanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_thanhToanActionPerformed(evt);
            }
        });

        jLabel_thanhTien.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_thanhTien.setForeground(new java.awt.Color(187, 0, 0));
        jLabel_thanhTien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_thanhTien.setText("000000");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Thành tiền");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_chiPhiPhong))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_chiPhiDichVu))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_thanhTien))
                    .addComponent(jButton_thanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_thongTinPhong))
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_thongTinDichVu))
                            .addComponent(jLabel11)
                            .addComponent(jLabel15))
                        .addGap(0, 90, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel_thongTinPhong))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel_chiPhiPhong))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel_thongTinDichVu))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel_chiPhiDichVu))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_thanhTien)
                .addGap(18, 18, 18)
                .addComponent(jButton_thanhToan)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách phòng đã thuê"));

        jTable_dsPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên khách hàng", "Căn cước", "Phòng thuê"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_dsPhong.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_dsPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_dsPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_dsPhong);
        if (jTable_dsPhong.getColumnModel().getColumnCount() > 0) {
            jTable_dsPhong.getColumnModel().getColumn(0).setResizable(false);
            jTable_dsPhong.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.dispose();
        TrangChu trangChu = new TrangChu();
        trangChu.show();
    }//GEN-LAST:event_formWindowClosed

    private void jTable_dsPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_dsPhongMouseClicked
        // TODO add your handling code here:
        visibility = true;
        int selectedRow = jTable_dsPhong.getSelectedRow();

        jLabel_tenKhachHang.setText(jTable_dsPhong.getValueAt(selectedRow, 0).toString());
        jLabel_canCuoc.setText(jTable_dsPhong.getValueAt(selectedRow, 1).toString());
        maPhong = jTable_dsPhong.getValueAt(selectedRow, 2).toString();
        laySoNgay(maPhong);
        jLabel_ngayDen.setText(ngayDen.toLocalDate().format(formatter));
        jLabel_ngayDi.setText(ngayDi.toLocalDate().format(formatter));
        jLabel_ngaySuDung.setText(Integer.toString(soNgay));
        jLabel_thongTinPhong.setText(layThongTin("SELECT HangPhong FROM phong WHERE MaPhong = ?", maPhong) + ", " + layThongTin("SELECT LoaiPhong FROM phong WHERE MaPhong = ?", maPhong));
        chiPhiPhong = layChiPhi("SELECT GiaThue FROM phong WHERE MaPhong = ?", maPhong) * soNgay;
        chiPhiDichVu = layChiPhi("SELECT dv.ChiPhi FROM phong_dichvu pdv JOIN dichvu dv ON pdv.MaDichVu = dv.MaDichVu WHERE pdv.MaPhong = ?", maPhong);
        thanhTien = chiPhiDichVu + chiPhiPhong;
        jLabel_chiPhiPhong.setText(Double.toString(chiPhiPhong) + " ₫");
        jLabel_thongTinDichVu.setText(layThongTin("SELECT COUNT(*) FROM phong_dichvu WHERE MaPhong = ?", maPhong));
        jLabel_chiPhiDichVu.setText(Double.toString(chiPhiDichVu) + " ₫");
        jLabel_thanhTien.setText(Double.toString(thanhTien) + " ₫");
        setVisibility(visibility);
    }//GEN-LAST:event_jTable_dsPhongMouseClicked

    private void jButton_thanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_thanhToanActionPerformed
        // TODO add your handling code here:
        String query = "INSERT INTO thanhtoan (MaThanhToan, MaKhachHang, MaPhong, TienPhong, TienDichVu, TongTien, ThoiDiemThanhToan, MaNhanVien) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        if (thanhTien != 0) {
            java.sql.Timestamp thoiDiemThanhToan = new java.sql.Timestamp(System.currentTimeMillis());
            try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                preparedStatement.setObject(1, GenericClass.generateRandomString("TT", 10000, 90000));
                preparedStatement.setObject(2, jLabel_canCuoc.getText());
                preparedStatement.setObject(3, maPhong);
                preparedStatement.setObject(4, chiPhiPhong);
                preparedStatement.setObject(5, chiPhiDichVu);
                preparedStatement.setObject(6, thanhTien);
                preparedStatement.setObject(7, thoiDiemThanhToan);
                preparedStatement.setObject(8, GenericClass.maNhanVien);
                if (preparedStatement.executeUpdate() >= 1) {
                    GenericClass.updateCSDL(connection, "DELETE FROM phieuden WHERE MaPhong = ?", maPhong);
//                    GenericClass.updateCSDL(connection, "DELETE FROM khachhang WHERE MaKhachHang = ?", jLabel_canCuoc.getText());
                    GenericClass.updateCSDL(connection, "DELETE FROM phong_dichvu WHERE MaPhong = ?", maPhong);
                    GenericClass.updateTinhTrangPhong(connection, maPhong, "Trống");
                    int luaChon = JOptionPane.showConfirmDialog(
                            this,
                            "Thanh toán phòng " + maPhong + " thành công" + "\n" + "Bạn có muốn in hóa đơn?",
                            "Xác nhận",
                            JOptionPane.YES_NO_OPTION);
                    if (luaChon == JOptionPane.YES_OPTION) {
//                        exportToExcel(maPhong, maPhong, chiPhiPhong, chiPhiDichVu, thanhTien);
                        JOptionPane.showMessageDialog(this, "It got some shit that need to be fixed", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Thanh toán phòng " + maPhong + " không thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi khi thanh toán.\n" + ex.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chọn khách hàng để thanh toán", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_thanhToanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThanhToan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_thanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_canCuoc;
    private javax.swing.JLabel jLabel_chiPhiDichVu;
    private javax.swing.JLabel jLabel_chiPhiPhong;
    private javax.swing.JLabel jLabel_ngayDen;
    private javax.swing.JLabel jLabel_ngayDi;
    private javax.swing.JLabel jLabel_ngaySuDung;
    private javax.swing.JLabel jLabel_tenKhachHang;
    private javax.swing.JLabel jLabel_thanhTien;
    private javax.swing.JLabel jLabel_thongTinDichVu;
    private javax.swing.JLabel jLabel_thongTinPhong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable_dsPhong;
    // End of variables declaration//GEN-END:variables
}
