/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlykhachsan_btl;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class ThuePhong extends javax.swing.JFrame {

    /**
     * Creates new form thuephong
     */
    Connection connection;
    String maPhieuDen;

    public ThuePhong() {
        initComponents();
        GenericClass.centerOnScreen(this);
        try {
            connection = DBConnector.connect();
        } catch (SQLException ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_dsKhach = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_dsDichVu = new javax.swing.JTable();
        jButton_themKhachMoi1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton_themKhachMoi = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jDateChooser_ngayDen = new com.toedter.calendar.JDateChooser();
        jLabel33 = new javax.swing.JLabel();
        jDateChooser_ngayDi = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_maKhachHang = new javax.swing.JTextField();
        jButton_thue = new javax.swing.JButton();
        jComboBox_maPhong = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField_timKiem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thuê phòng");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách khách đã đặt phòng trước", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTable_dsKhach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ tên", "Số điện thoại", "Căn cước", "Phòng", "Ngày đến", "Ngày đi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_dsKhach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_dsKhach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_dsKhachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_dsKhach);
        if (jTable_dsKhach.getColumnModel().getColumnCount() > 0) {
            jTable_dsKhach.getColumnModel().getColumn(0).setResizable(false);
            jTable_dsKhach.getColumnModel().getColumn(1).setResizable(false);
            jTable_dsKhach.getColumnModel().getColumn(2).setResizable(false);
            jTable_dsKhach.getColumnModel().getColumn(3).setResizable(false);
            jTable_dsKhach.getColumnModel().getColumn(4).setResizable(false);
            jTable_dsKhach.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách dịch vụ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTable_dsDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Chi phí"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_dsDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_dsDichVuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_dsDichVu);
        if (jTable_dsDichVu.getColumnModel().getColumnCount() > 0) {
            jTable_dsDichVu.getColumnModel().getColumn(0).setResizable(false);
            jTable_dsDichVu.getColumnModel().getColumn(1).setResizable(false);
            jTable_dsDichVu.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton_themKhachMoi1.setText("Quản lý dịch vụ");
        jButton_themKhachMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_themKhachMoi1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addComponent(jButton_themKhachMoi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_themKhachMoi1)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lập phiếu đến"));

        jButton_themKhachMoi.setText("Thêm khách hàng mới");
        jButton_themKhachMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_themKhachMoiActionPerformed(evt);
            }
        });

        jLabel32.setText("Ngày đến:");

        jDateChooser_ngayDen.setFocusable(false);

        jLabel33.setText("Ngày đi:");

        jLabel2.setText("Phòng:");

        jLabel3.setText("Căn cước công dân:");

        jTextField_maKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_KeyTyped(evt);
            }
        });

        jButton_thue.setText("Thuê phòng");
        jButton_thue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_thueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox_maPhong, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser_ngayDen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser_ngayDi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(155, 155, 155))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(223, 223, 223))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(217, 217, 217))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_thue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_themKhachMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField_maKhachHang))
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_maKhachHang)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_maPhong)
                .addGap(18, 18, 18)
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser_ngayDen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser_ngayDi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_thue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_themKhachMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setText("Tìm kiếm khách đã đặt phòng:");

        jTextField_timKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_timKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_timKiem))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clear_input() {
        jTextField_maKhachHang.requestFocus();
        jTextField_maKhachHang.setText("");
        jComboBox_maPhong.setSelectedIndex(0);
        jDateChooser_ngayDen.setDate(null);
        jDateChooser_ngayDi.setDate(null);
    }

    private void loadMaPhongTrong() {
        try {
            jComboBox_maPhong.removeAllItems();
            String query = "SELECT MaPhong FROM phong WHERE TinhTrang = 'Đã đặt'";
            try (Statement statement = connection.createStatement(); ResultSet resultSet = statement.executeQuery(query)) {

                while (resultSet.next()) {
                    String maPhong = resultSet.getString("MaPhong");
                    jComboBox_maPhong.addItem(maPhong);
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void themDichVu(int[] selectedRow, String maPhong, java.sql.Timestamp thoiDiemYeuCau) {
        try {
            int[] _selectedRows = selectedRow;
            for (int rowIndex : _selectedRows) {
                String maDichVu = jTable_dsDichVu.getValueAt(rowIndex, 0).toString();
                String queryInsert = "INSERT INTO phong_dichvu(MaPhong, MaDichVu, ThoiDiemYeuCau) VALUES (?, ?, ?)";
                try (java.sql.PreparedStatement preparedStatement = connection.prepareStatement(queryInsert)) {
                    preparedStatement.setString(1, maPhong);
                    preparedStatement.setString(2, maDichVu);
                    preparedStatement.setTimestamp(3, thoiDiemYeuCau);

                    preparedStatement.executeUpdate();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        } catch (HeadlessException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi đặt phòng.", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void jTable_dsKhachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_dsKhachMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_dsKhach.getSelectedRow();
        jTextField_maKhachHang.setText(jTable_dsKhach.getValueAt(selectedRow, 2).toString());
        jComboBox_maPhong.setSelectedItem(jTable_dsKhach.getValueAt(selectedRow, 3).toString());
        Object ngayDenValue = jTable_dsKhach.getValueAt(selectedRow, 4);
        if (ngayDenValue instanceof java.time.LocalDateTime) {
            java.time.LocalDateTime ngayDenLocalDateTime = (java.time.LocalDateTime) ngayDenValue;
            java.util.Date ngayDenDate = java.sql.Timestamp.valueOf(ngayDenLocalDateTime);
            jDateChooser_ngayDen.setDate(ngayDenDate);
        }
        Object ngayDiValue = jTable_dsKhach.getValueAt(selectedRow, 5);
        if (ngayDiValue instanceof java.time.LocalDateTime) {
            java.time.LocalDateTime ngayDiLocalDateTime = (java.time.LocalDateTime) ngayDiValue;
            java.util.Date ngayDiDate = java.sql.Timestamp.valueOf(ngayDiLocalDateTime);
            jDateChooser_ngayDi.setDate(ngayDiDate);
        }
    }//GEN-LAST:event_jTable_dsKhachMouseClicked

    private void jTable_dsDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_dsDichVuMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_dsDichVu.getSelectedRow();
    }//GEN-LAST:event_jTable_dsDichVuMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        maPhieuDen = GenericClass.generateRandomString("pd", 1000, 9000);
        GenericClass.loadData(connection, "SELECT kh.HoTen, kh.SoDienThoai, kh.MaKhachHang, p.MaPhong, kh.NgayDen, kh.NgayDi FROM khachhang kh JOIN phong p ON kh.MaPhong = p.MaPhong WHERE p.TinhTrang = 'Đã đặt'", jTable_dsKhach);
        GenericClass.loadData(connection, GenericClass.selectDichVu, jTable_dsDichVu);
        loadMaPhongTrong();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.dispose();
        TrangChu trangChu = new TrangChu();
        trangChu.show();
    }//GEN-LAST:event_formWindowClosed

    private void jButton_themKhachMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_themKhachMoiActionPerformed
        // TODO add your handling code here:
        DatPhong datPhong = new DatPhong();
        this.hide();
        datPhong.show();
        GenericClass.isFromThuePhong = true;
    }//GEN-LAST:event_jButton_themKhachMoiActionPerformed

    private void jButton_thueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_thueActionPerformed
        // TODO add your handling code here:
        int[] selectedRows = jTable_dsDichVu.getSelectedRows();
        String maPhong = jComboBox_maPhong.getSelectedItem().toString();
        java.sql.Timestamp thoiDiemYeuCau = new java.sql.Timestamp(System.currentTimeMillis());
        try {
            String maKhachHang = jTextField_maKhachHang.getText();
            Date ngayDen = GenericClass.getDateFromDateChooser(jDateChooser_ngayDen);
            Date ngayDi = GenericClass.getDateFromDateChooser(jDateChooser_ngayDi);

            // Kiểm tra nếu một trong các trường là trống
            if (maKhachHang.isEmpty() || jComboBox_maPhong.getSelectedIndex() < 0 || jDateChooser_ngayDen.getDate() == null || jDateChooser_ngayDi.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else if (ngayDen.after(ngayDi)) {
                // Kiểm tra nếu ngày đến sau ngày đi
                JOptionPane.showMessageDialog(this, "Ngày đến phải trước ngày đi.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else {
                // Thêm dữ liệu vào cơ sở dữ liệu
                String query = "INSERT INTO phieuden(MaPhieu, MaKhachHang, MaPhong, NgayDen, NgayDi) VALUES (?, ?, ?, ?, ?)";
                try (java.sql.PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                    preparedStatement.setString(1, maPhieuDen);
                    preparedStatement.setString(2, maKhachHang);
                    preparedStatement.setString(3, maPhong);
                    preparedStatement.setDate(4, new java.sql.Date(ngayDen.getTime()));
                    preparedStatement.setDate(5, new java.sql.Date(ngayDi.getTime()));

                    // Thực hiện câu lệnh SQL
                    preparedStatement.executeUpdate();
                }
                clear_input();
                GenericClass.updateTinhTrangPhong(connection, maPhong, "Đã thuê");
                JOptionPane.showMessageDialog(this, "Thuê phòng " + maPhong + " thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (HeadlessException | NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi đặt phòng.", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        if (selectedRows != null){
            themDichVu(selectedRows, maPhong, thoiDiemYeuCau);
        }
    }//GEN-LAST:event_jButton_thueActionPerformed

    private void jTextField_timKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_timKiemKeyReleased
        // TODO add your handling code here:
        String query = "SELECT kh.HoTen, kh.SoDienThoai, kh.MaKhachHang, kh.NgayDen, kh.NgayDi, p.MaPhong FROM khachhang kh JOIN phong p ON kh.MaPhong = p.MaPhong WHERE p.TinhTrang = 'Đã đặt' AND kh.MaKhachHang LIKE '%" + jTextField_timKiem.getText() + "%'";
        GenericClass.loadData(connection, query, jTable_dsKhach);
    }//GEN-LAST:event_jTextField_timKiemKeyReleased

    private void jTextField_KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_KeyTyped
        // TODO add your handling code here:
        GenericClass.numbersOnly(evt);
    }//GEN-LAST:event_jTextField_KeyTyped

    private void jButton_themKhachMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_themKhachMoi1ActionPerformed
        // TODO add your handling code here:
        QuanLyDichVu quanLyDichVu = new QuanLyDichVu();
        quanLyDichVu.show();
    }//GEN-LAST:event_jButton_themKhachMoi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThuePhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThuePhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThuePhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThuePhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThuePhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_themKhachMoi;
    private javax.swing.JButton jButton_themKhachMoi1;
    private javax.swing.JButton jButton_thue;
    private javax.swing.JComboBox<String> jComboBox_maPhong;
    private com.toedter.calendar.JDateChooser jDateChooser_ngayDen;
    private com.toedter.calendar.JDateChooser jDateChooser_ngayDi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_dsDichVu;
    private javax.swing.JTable jTable_dsKhach;
    private javax.swing.JTextField jTextField_maKhachHang;
    private javax.swing.JTextField jTextField_timKiem;
    // End of variables declaration//GEN-END:variables

}
