/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlykhachsan_btl;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author itsHuaan
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    Connection connection;

    public TrangChu() {
        initComponents();
        jTable_dsphong.setRowSelectionAllowed(false);
        GenericClass.centerOnScreen(this);
        try {
            connection = DBConnector.connect();
        } catch (SQLException ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon icon = new ImageIcon(TrangChu.class.getResource("/img/logout.png"));
        Image scaledImage = icon.getImage().getScaledInstance(jButton_thoat.getWidth(), jButton_thoat.getHeight(), Image.SCALE_SMOOTH);
        jButton_thoat.setIcon(new ImageIcon(scaledImage));
    }

    private void loadSoLuongPhong(String query, String tinhTrang, JLabel label) {
        if (connection != null) {
            try (java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                statement.setString(1, tinhTrang);
                try (ResultSet resultSet = statement.executeQuery()) {
                    if (resultSet.next()) {
                        int soLuong = resultSet.getInt("SoLuong");
                        label.setText(Integer.toString(soLuong));
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Kết nối thất bại");
        }
    }

    private void loadPhong(String query) {
        try {
            // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) jTable_dsphong.getModel();
            model.setRowCount(0);

            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery(query);

            while (resultSet.next()) {
                Object[] col = new Object[6];
                col[0] = resultSet.getObject(1);
                col[1] = resultSet.getObject(2);
                col[2] = resultSet.getObject(3);
                col[3] = resultSet.getObject(4);
                col[4] = resultSet.getObject(5);
                col[5] = resultSet.getObject(6);
                model.addRow(col);
            }

            resultSet.close();
            statement.close();
        } catch (SQLException ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @SuppressWarnings("deprecation")
    private void thoat() {
        GenericClass.XoaPhienDangNhap();
        this.dispose();
        DangNhap dangNhap = new DangNhap();
        dangNhap.show();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_nguoiDung = new javax.swing.JLabel();
        jButton_datPhong = new javax.swing.JButton();
        jButton_quanLyPhong = new javax.swing.JButton();
        jButton_thoat = new javax.swing.JButton();
        jButton_thongKe = new javax.swing.JButton();
        jButton_quanLyKhach = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton_thuePhong = new javax.swing.JButton();
        jButton_thanhToan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_phongDaThue = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_phongDaDat = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel_phongTrong = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_dsphong = new javax.swing.JTable();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trang chủ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel_nguoiDung.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_nguoiDung.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nguoiDung.setText("Xin chào");

        jButton_datPhong.setBackground(new java.awt.Color(102, 102, 102));
        jButton_datPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_datPhong.setForeground(new java.awt.Color(255, 255, 255));
        jButton_datPhong.setText("   Đặt phòng");
        jButton_datPhong.setBorder(null);
        jButton_datPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_datPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_datPhongActionPerformed(evt);
            }
        });

        jButton_quanLyPhong.setBackground(new java.awt.Color(102, 102, 102));
        jButton_quanLyPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_quanLyPhong.setForeground(new java.awt.Color(255, 255, 255));
        jButton_quanLyPhong.setBorder(null);
        jButton_quanLyPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_quanLyPhong.setLabel("   Quản lý phòng");
        jButton_quanLyPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_quanLyPhongActionPerformed(evt);
            }
        });

        jButton_thoat.setBackground(new java.awt.Color(102, 102, 102));
        jButton_thoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_thoat.setForeground(new java.awt.Color(255, 255, 255));
        jButton_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jButton_thoat.setBorder(null);
        jButton_thoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_thoatActionPerformed(evt);
            }
        });

        jButton_thongKe.setBackground(new java.awt.Color(102, 102, 102));
        jButton_thongKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_thongKe.setForeground(new java.awt.Color(255, 255, 255));
        jButton_thongKe.setText("   Thống kê");
        jButton_thongKe.setBorder(null);
        jButton_thongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_thongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_thongKeActionPerformed(evt);
            }
        });

        jButton_quanLyKhach.setBackground(new java.awt.Color(102, 102, 102));
        jButton_quanLyKhach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_quanLyKhach.setForeground(new java.awt.Color(255, 255, 255));
        jButton_quanLyKhach.setText("   Quản lý khách hàng");
        jButton_quanLyKhach.setBorder(null);
        jButton_quanLyKhach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_quanLyKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_quanLyKhachActionPerformed(evt);
            }
        });

        jButton_thuePhong.setBackground(new java.awt.Color(102, 102, 102));
        jButton_thuePhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_thuePhong.setForeground(new java.awt.Color(255, 255, 255));
        jButton_thuePhong.setText("   Thuê phòng");
        jButton_thuePhong.setBorder(null);
        jButton_thuePhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_thuePhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_thuePhongActionPerformed(evt);
            }
        });

        jButton_thanhToan.setBackground(new java.awt.Color(102, 102, 102));
        jButton_thanhToan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_thanhToan.setForeground(new java.awt.Color(255, 255, 255));
        jButton_thanhToan.setText("   Thanh toán");
        jButton_thanhToan.setBorder(null);
        jButton_thanhToan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_thanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_thanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel_nguoiDung))
                    .addComponent(jButton_quanLyPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_datPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_thongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_quanLyKhach, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jButton_thuePhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButton_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton_thanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel_nguoiDung)
                .addGap(51, 51, 51)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_quanLyPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_quanLyKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_datPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_thuePhong, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_thanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_thongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phòng đã thuê", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel_phongDaThue.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel_phongDaThue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_phongDaThue.setText("00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel_phongDaThue)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel_phongDaThue)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phòng đã đặt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel_phongDaDat.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel_phongDaDat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_phongDaDat.setText("00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel_phongDaDat)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel_phongDaDat)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phòng trống", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel_phongTrong.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel_phongTrong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_phongTrong.setText("00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel_phongTrong)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel_phongTrong)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách phòng"));

        jTable_dsphong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Loại phòng", "Hạng phòng", "Vị trí", "Giá thuê", "Tình trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_dsphong);
        if (jTable_dsphong.getColumnModel().getColumnCount() > 0) {
            jTable_dsphong.getColumnModel().getColumn(0).setResizable(false);
            jTable_dsphong.getColumnModel().getColumn(1).setResizable(false);
            jTable_dsphong.getColumnModel().getColumn(2).setResizable(false);
            jTable_dsphong.getColumnModel().getColumn(3).setResizable(false);
            jTable_dsphong.getColumnModel().getColumn(4).setResizable(false);
            jTable_dsphong.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Sự kiện của các components">
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jLabel_nguoiDung.setText("<html>Xin chào<br>" + GenericClass.hoTen + "</html>");
        loadPhong(GenericClass.selectPhong);
        loadSoLuongPhong(GenericClass.loadSoLuongPhong, "Trống", jLabel_phongTrong);
        loadSoLuongPhong(GenericClass.loadSoLuongPhong, "Đã đặt", jLabel_phongDaDat);
        loadSoLuongPhong(GenericClass.loadSoLuongPhong, "Đã thuê", jLabel_phongDaThue);
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        thoat();
    }//GEN-LAST:event_formWindowClosed

    @SuppressWarnings("deprecation")
    private void jButton_quanLyPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_quanLyPhongActionPerformed
        // TODO add your handling code here:
        QuanLyPhong quanLyPhong = new QuanLyPhong();
        this.hide();
        quanLyPhong.show();
    }//GEN-LAST:event_jButton_quanLyPhongActionPerformed

    private void jButton_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_thoatActionPerformed
        // TODO add your handling code here:
        int luaChon = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn thoát?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);

        // Kiểm tra xem người dùng đã chọn Yes hay No
        if (luaChon == JOptionPane.YES_OPTION) {
            thoat();
        }
    }//GEN-LAST:event_jButton_thoatActionPerformed

    @SuppressWarnings("deprecation")
    private void jButton_datPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_datPhongActionPerformed
        // TODO add your handling code here:
        DatPhong datPhong = new DatPhong();
        this.hide();
        datPhong.show();
    }//GEN-LAST:event_jButton_datPhongActionPerformed

    @SuppressWarnings("deprecation")
    private void jButton_quanLyKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_quanLyKhachActionPerformed
        // TODO add your handling code here:
        QuanLyKhachHang khachHang = new QuanLyKhachHang();
        this.hide();
        khachHang.show();
    }//GEN-LAST:event_jButton_quanLyKhachActionPerformed

    private void jButton_thuePhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_thuePhongActionPerformed
        // TODO add your handling code here:
        ThuePhong thuePhong = new ThuePhong();
        this.hide();
        thuePhong.show();
    }//GEN-LAST:event_jButton_thuePhongActionPerformed

    private void jButton_thanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_thanhToanActionPerformed
        // TODO add your handling code here:
        ThanhToan thanhToan = new ThanhToan();
        this.hide();
        thanhToan.show();
    }//GEN-LAST:event_jButton_thanhToanActionPerformed

    private void jButton_thongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_thongKeActionPerformed
        // TODO add your handling code here:
        ThongKe thongKe = new ThongKe();
        this.hide();
        thongKe.show();
    }//GEN-LAST:event_jButton_thongKeActionPerformed
    //</editor-fold>
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_datPhong;
    private javax.swing.JButton jButton_quanLyKhach;
    private javax.swing.JButton jButton_quanLyPhong;
    private javax.swing.JButton jButton_thanhToan;
    private javax.swing.JButton jButton_thoat;
    private javax.swing.JButton jButton_thongKe;
    private javax.swing.JButton jButton_thuePhong;
    private javax.swing.JLabel jLabel_nguoiDung;
    private javax.swing.JLabel jLabel_phongDaDat;
    private javax.swing.JLabel jLabel_phongDaThue;
    private javax.swing.JLabel jLabel_phongTrong;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable_dsphong;
    // End of variables declaration//GEN-END:variables
}
